[package]
name = "opensrf"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.4"
chrono = "0.4.19"
yaml-rust = "0.4.5"
log = "0.4.14"
log4rs = "1.1.1"
json = "0.12.4"
roxmltree = "0.14.1"
redis = "0.21.4"
tungstenite = "0.16.0"

